Pkg.update()
Pkg.add("HttpServer")
Pkg.add("Logging")
Pkg.add("Markdown")
Pkg.clone("https://github.com/JuliaComputing/MySQL.jl")
Pkg.clone("https://github.com/PhoenixMachina/Tlaloc")
Pkg.add("SecureSessions")
